repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: requirements.txt
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: "23.9.0"
    hooks:
      - id: black
        exclude: (migrations)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
        exclude: migrations
